name: Copy files to cluster

on:
  push:
    branches:
      - main

jobs:
  copy_files:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Create SSH directory
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

    - name: Add host key to known hosts
      run: |
        touch ~/.ssh/known_hosts
        if test -f ~/.ssh/known_hosts; then
          echo "File exists"
        else
          echo "File does not exist"
        fi
        ssh-keyscan txe1-login.mit.edu >> ~/.ssh/known_hosts
    
    - name: Copy files to cluster
      run: |
        if [ -n "${{ secrets.CLUSTER_SSH_PRIVATE_KEY }}" ]; then
          echo "${{ secrets.CLUSTER_SSH_PRIVATE_KEY }}"
        else
          echo "CLUSTER_SSH_PRIVATE_KEY does not exist."
        fi
        scp -i ${{ secrets.CLUSTER_SSH_PRIVATE_KEY }} -r . jsass@txe1-login.mit.edu:/home/gridsan/jsass/idp_linkerizer
